### ISSUE TITLE
RoundManager: Uncaught Error: useRoutes() may be used only in the context of a <Router> component.  

### ISSUE THREAD

**Issue by carlbarrdahl** [gitcoinco/grants-stack#1921]
**Overview**
Running the RoundManager returns a blank white page. Console.log says:
```sh
Uncaught Error: useRoutes() may be used only in the context of a <Router> component.
    at invariant (history.ts:480:11)
    at useRoutes (hooks.tsx:307:12)
    at Routes (components.tsx:393:10)
    at renderWithHooks (react-dom.development.js:16305:1)
    at mountIndeterminateComponent (react-dom.development.js:20074:1)
    at beginWork (react-dom.development.js:21587:1)
    at HTMLUnknownElement.callCallback (react-dom.development.js:4164:1)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:4213:1)
    at invokeGuardedCallback (react-dom.development.js:4277:1)
    at beginWork$1 (react-dom.development.js:27451:1)
i
```

**Steps To Reproduce**
1. `git clone git@github.com:gitcoinco/grants-stack.git`
2. `pnpm i`
3. `cd packages/round-manager`
4. Configure `.env` variables
5. `npm start`

**Observed  behavior**
Page doesn't load

**Expected behavior**
Page loads correctly

**Screenshots**
![image](https://github.com/gitcoinco/grants-stack/assets/2961337/a8f5610f-f6f8-4fa9-a734-eaf3ee1a2ebd)

**Additional context**
Builder package works as expected

**Comment by gravityblast** [comment]
@gitcoinco/grantsstack-engineering I think we can close this issue since we don't have this problem anymore, do you feel we need any change anyway?

**Comment by bard** [comment]
@gravityblast no longer happening, I'm closing.
