### ISSUE TITLE
Builder: Error after round application

### ISSUE THREAD

**Issue by gravityblast** [gitcoinco/grants-stack#2091]
After applying to a round on PGN mainnet, I was redirected to my project page and saw the following error in the browser console. Everything was working correctly anyway.
(note that `0xDF9BF58Aa1A1B73F0e214d79C652a7dd37a6074e` is the ProjectRegistry address on PGN)
```
failed fetchProjectApplications for Project Id 424:0xDF9BF58Aa1A1B73F0e214d79C652a7dd37a6074e:0 in Chain Id 1 Error: invalid BigNumber string (argument="value", value="424:0xDF9BF58Aa1A1B73F0e214d79C652a7dd37a6074e:0", code=INVALID_ARGUMENT, version=bignumber/5.7.0)
    at p.makeError (index.ts:269:28)
    at p.throwError (index.ts:281:20)
    at p.throwArgumentError (index.ts:285:21)
    at p.from (bignumber.ts:238:27)
    at w (index.ts:46:17)
    at index.ts:90:20
    at Array.forEach (<anonymous>)
    at A (index.ts:89:11)
    at Module.P (index.ts:96:26)
    at D2 (roundApplication.ts:13:3)
console.<computed> @ consoleObservable.ts:34
consoleObservable.ts:34 failed fetchProjectApplications for Project Id 424:0xDF9BF58Aa1A1B73F0e214d79C652a7dd37a6074e:0 in Chain Id 250 Error: invalid BigNumber string (argument="value", value="424:0xDF9BF58Aa1A1B73F0e214d79C652a7dd37a6074e:0", code=INVALID_ARGUMENT, version=bignumber/5.7.0)
    at p.makeError (index.ts:269:28)
    at p.throwError (index.ts:281:20)
    at p.throwArgumentError (index.ts:285:21)
    at p.from (bignumber.ts:238:27)
    at w (index.ts:46:17)
    at index.ts:90:20
    at Array.forEach (<anonymous>)
    at A (index.ts:89:11)
    at Module.P (index.ts:96:26)
    at D2 (roundApplication.ts:13:3)
console.<computed> @ consoleObservable.ts:34
consoleObservable.ts:34 failed fetchProjectApplications for Project Id 424:0xDF9BF58Aa1A1B73F0e214d79C652a7dd37a6074e:0 in Chain Id 10 Error: invalid BigNumber string (argument="value", value="424:0xDF9BF58Aa1A1B73F0e214d79C652a7dd37a6074e:0", code=INVALID_ARGUMENT, version=bignumber/5.7.0)
    at p.makeError (index.ts:269:28)
    at p.throwError (index.ts:281:20)
    at p.throwArgumentError (index.ts:285:21)
    at p.from (bignumber.ts:238:27)
    at w (index.ts:46:17)
    at index.ts:90:20
    at Array.forEach (<anonymous>)
    at A (index.ts:89:11)
    at Module.P (index.ts:96:26)
    at D2 (roundApplication.ts:13:3)
console.<computed> @ consoleObservable.ts:34
consoleObservable.ts:34 failed fetchProjectApplications for Project Id 424:0xDF9BF58Aa1A1B73F0e214d79C652a7dd37a6074e:0 in Chain Id 424 Error: invalid BigNumber string (argument="value", value="424:0xDF9BF58Aa1A1B73F0e214d79C652a7dd37a6074e:0", code=INVALID_ARGUMENT, version=bignumber/5.7.0)
    at p.makeError (index.ts:269:28)
    at p.throwError (index.ts:281:20)
    at p.throwArgumentError (index.ts:285:21)
    at p.from (bignumber.ts:238:27)
    at w (index.ts:46:17)
    at index.ts:90:20
    at Array.forEach (<anonymous>)
    at A (index.ts:89:11)
    at Module.P (index.ts:96:26)
```

**Comment by meg-fsc** [comment]
@michellema1208 I'm going to move this to low because it is not impacting users directly
