### ISSUE TITLE
Donations from Beta round missing in history page

### ISSUE THREAD

**Issue by jesuloluwao** [gitcoinco/grants-stack#2738]
### What was the URL where the error occurred?

https://explorer.gitcoin.co/#/contributors/0x69f9e121702461eA52F627A6147ea3c6dc2DEF31

### What happened?

User reported that they can't find their donations from the Beta round in the donations history page.

I confirmed that I can't find my donations too. Also, I see that my total donations has reduced (was over $100) before. https://explorer.gitcoin.co/#/contributors/0x69f9e121702461eA52F627A6147ea3c6dc2DEF31

Here are some donations from beta round:
- https://etherscan.io/tx/0xaef536fcbe84c543777225fa9e8a2031c8f3ab9dd8ddb61e9a09a88fbe627573
- https://etherscan.io/tx/0xa1ff6787ee306270ded6187b7e05e2a88f18a96614dd0c8829894fdade1e9a2d
- https://etherscan.io/tx/0xbfde58ea2b6499e1895d7d5b2f11f1753b84b1695c87fdd8d32cb6f313851cc1

Also, I see this error on the console log saying "Error fetching contribution history for chain 1", pointing to one of my transactions
![image](https://github.com/gitcoinco/grants-stack/assets/88308638/99b3f972-4079-4755-8b06-38c2afbb0e83)

**Link:** [Conversation with Dave Dave](https://app.intercom.com/a/apps/xaafeyri/inbox/inbox/all/conversations/68367)

**Customer:** [Dave Dave](https://app.intercom.com/a/apps/xaafeyri/users/6572f46b6fab75ad037506b1/all-conversations)
**Customer ID:** 075b43b5-b14c-4ab9-8a9b-7c57ad2d2289
___
Intercom Operator will send a note to [this conversation](https://app.intercom.com/a/apps/xaafeyri/inbox/inbox/all/conversations/68367) when this issue is closed.

### What should have happened instead?

I should see all my on chain donations

### Steps to Reproduce

Browse to your donation history and check donations from Alpha/Beta rounds

### What browser(s) are you seeing the problem on?

Chrome

### What chain(s) did the error occur on?

N/A

### Relevant log output

```shell
instrument.ts:174 
        
        
       GET https://d1lxlknxcoh5cw.cloudfront.net/data/43114/contributors/0x69f9/e12170/2461eA/52F627/A6147e/a3c6dc/2DEF31.json 404 (Not Found)
(anonymous) @ instrument.ts:174
(anonymous) @ fetchObservable.ts:55
c @ instrumentMethod.ts:21
fetchResources @ baseClient.js:23
getContributionsByAddress @ client.js:76
(anonymous) @ round.ts:208
(anonymous) @ round.ts:189
(anonymous) @ round.ts:254
gi @ react-dom.production.min.js:244
Qf @ react-dom.production.min.js:286
mb @ react-dom.production.min.js:273
td @ react-dom.production.min.js:127
vb @ react-dom.production.min.js:283
$d @ react-dom.production.min.js:281
vy @ react-dom.production.min.js:270
N @ scheduler.production.min.js:13
oe @ scheduler.production.min.js:14
instrument.ts:144 Error fetching contribution history for chain 43114: ResourceFetchError: cannot fetch resource at route "contributions"
    at HW.fetchResources (baseClient.js:32:19)
    at async Promise.all (/index 5)
    at async round.ts:242:28
instrument.ts:174 
        
        
       GET https://d1lxlknxcoh5cw.cloudfront.net/data/250/contributors/0x69f9/e12170/2461eA/52F627/A6147e/a3c6dc/2DEF31.json 404 (Not Found)
(anonymous) @ instrument.ts:174
(anonymous) @ fetchObservable.ts:55
c @ instrumentMethod.ts:21
fetchResources @ baseClient.js:23
getContributionsByAddress @ client.js:76
(anonymous) @ round.ts:208
(anonymous) @ round.ts:189
(anonymous) @ round.ts:254
gi @ react-dom.production.min.js:244
Qf @ react-dom.production.min.js:286
mb @ react-dom.production.min.js:273
td @ react-dom.production.min.js:127
vb @ react-dom.production.min.js:283
$d @ react-dom.production.min.js:281
vy @ react-dom.production.min.js:270
N @ scheduler.production.min.js:13
oe @ scheduler.production.min.js:14
instrument.ts:144 Error fetching contribution history for chain 250: ResourceFetchError: cannot fetch resource at route "contributions"
    at HW.fetchResources (baseClient.js:32:19)
    at async Promise.all (/index 2)
    at async round.ts:242:28
instrument.ts:144 Error fetching contribution history for chain 1: TransactionNotFoundError: Transaction with hash "0xbfde58ea2b6499e1895d7d5b2f11f1753b84b1695c87fdd8d32cb6f313851cc1" could not be found.

Version: viem@1.10.6
    at ll (getTransaction.ts:117:11)
    at async round.ts:210:24
    at async Promise.all (/index 0)
    at async round.ts:209:32
    at async Promise.all (/index 0)
    at async round.ts:242:28
instrument.ts:144 {context: 'core'} {context: 'core/verify-api'} 'Verify iframe failed to load: https://verify.walletconnect.org'
(anonymous) @ instrument.ts:144
bd.<computed> @ consoleObservable.ts:40
(anonymous) @ browser.js:202
(anonymous) @ browser.js:266
(anonymous) @ browser.js:266
Kf.init @ 407.a58d28e5.chunk.js:1
await in Kf.init (async)
initialize @ 407.a58d28e5.chunk.js:7
await in initialize (async)
init @ 407.a58d28e5.chunk.js:7
createClient @ lodash.js:10
initialize @ lodash.js:10
init @ lodash.js:10
initialize @ 407.a58d28e5.chunk.js:33
init @ 407.a58d28e5.chunk.js:33
qL @ walletConnect.js:235
await in qL (async)
_x @ walletConnect.js:219
Px @ walletConnect.js:65
tbe @ chunk-L5I2KKMA.js:13
Rx @ chunk-L5I2KKMA.js:43
createConnector @ chunk-2X2KWBQI.js:23
(anonymous) @ index.js:96
(anonymous) @ index.js:73
B4 @ chunk-LAFZBYO7.js:398
us @ chunk-LAFZBYO7.js:636
Yf @ index.js:37
(anonymous) @ wagmi.ts:41
(anonymous) @ main.6b3584fa.js:1211
(anonymous) @ main.6b3584fa.js:1211
instrument.ts:144 {context: 'core'} {context: 'core/verify-api'} 'verify iframe load timeout'
(anonymous) @ instrument.ts:144
bd.<computed> @ consoleObservable.ts:40
(anonymous) @ browser.js:202
(anonymous) @ browser.js:266
(anonymous) @ browser.js:266
Kf.init @ 407.a58d28e5.chunk.js:1
await in Kf.init (async)
initialize @ 407.a58d28e5.chunk.js:7
await in initialize (async)
init @ 407.a58d28e5.chunk.js:7
createClient @ lodash.js:10
initialize @ lodash.js:10
init @ lodash.js:10
initialize @ 407.a58d28e5.chunk.js:33
init @ 407.a58d28e5.chunk.js:33
qL @ walletConnect.js:235
await in qL (async)
_x @ walletConnect.js:219
Px @ walletConnect.js:65
tbe @ chunk-L5I2KKMA.js:13
Rx @ chunk-L5I2KKMA.js:43
createConnector @ chunk-2X2KWBQI.js:23
(anonymous) @ index.js:96
(anonymous) @ index.js:73
B4 @ chunk-LAFZBYO7.js:398
us @ chunk-LAFZBYO7.js:636
Yf @ index.js:37
(anonymous) @ wagmi.ts:41
(anonymous) @ main.6b3584fa.js:1211
(anonymous) @ main.6b3584fa.js:1211
fetch.ts:45 
        
        
       POST https://o4504301442957312.ingest.sentry.io/api/4504327111114752/envelope/?sentry_key=ee69541af52845019ba7289440b22a76&sentry_version=7&sentry_client=sentry.javascript.react%2F7.68.0 429 (Too Many Requests)
o @ fetch.ts:45
P @ base.ts:76
o @ promisebuffer.ts:49
c @ base.ts:92
_sendEnvelope @ baseclient.ts:713
sendEvent @ baseclient.ts:340
(anonymous) @ baseclient.ts:669
(anonymous) @ syncpromise.ts:82
(anonymous) @ syncpromise.ts:186
_executeHandlers @ syncpromise.ts:179
(anonymous) @ syncpromise.ts:100
w @ syncpromise.ts:61
then @ syncpromise.ts:72
_processEvent @ baseclient.ts:646
_captureEvent @ baseclient.ts:570
(anonymous) @ baseclient.ts:181
(anonymous) @ syncpromise.ts:82
(anonymous) @ syncpromise.ts:186
_executeHandlers @ syncpromise.ts:179
(anonymous) @ syncpromise.ts:100
w @ syncpromise.ts:61
then @ syncpromise.ts:72
captureMessage @ baseclient.ts:181
(anonymous) @ hub.ts:226
_withClient @ hub.ts:493
captureMessage @ hub.ts:225
(anonymous) @ captureconsole.ts:88
withScope @ hub.ts:165
o1e @ captureconsole.ts:63
(anonymous) @ captureconsole.ts:57
W @ instrument.ts:115
(anonymous) @ instrument.ts:141
bd.<computed> @ consoleObservable.ts:40
(anonymous) @ browser.js:202
(anonymous) @ browser.js:266
(anonymous) @ browser.js:266
Kf.init @ 407.a58d28e5.chunk.js:1
await in Kf.init (async)
initialize @ 407.a58d28e5.chunk.js:7
await in initialize (async)
init @ 407.a58d28e5.chunk.js:7
createClient @ lodash.js:10
initialize @ lodash.js:10
init @ lodash.js:10
initialize @ 407.a58d28e5.chunk.js:33
init @ 407.a58d28e5.chunk.js:33
qL @ walletConnect.js:235
await in qL (async)
_x @ walletConnect.js:219
Px @ walletConnect.js:65
tbe @ chunk-L5I2KKMA.js:13
Rx @ chunk-L5I2KKMA.js:43
createConnector @ chunk-2X2KWBQI.js:23
(anonymous) @ index.js:96
(anonymous) @ index.js:73
B4 @ chunk-LAFZBYO7.js:398
us @ chunk-LAFZBYO7.js:636
Yf @ index.js:37
(anonymous) @ wagmi.ts:41
(anonymous) @ main.6b3584fa.js:1211
(anonymous) @ main.6b3584fa.js:1211
fetch.ts:45 
        
        
       POST https://o4504301442957312.ingest.sentry.io/api/4504327111114752/envelope/?sentry_key=ee69541af52845019ba7289440b22a76&sentry_version=7&sentry_client=sentry.javascript.react%2F7.68.0 429 (Too Many Requests)
```

**Comment by vacekj** [comment]
@jesuloluwao I have just verified that the txs you posted as examples are indeed showing up in your contribution history page. I am going to ascribe this to a temporary indexer failure, but please do check if the issue persists for you, and feel free to reopen the issue with additional details or reproduction steps. Thanks!
