### ISSUE TITLE
Manager - SEI round not loading applications

### ISSUE THREAD

**Issue by MasterHW** [gitcoinco/grants-stack#3656]
### What was the URL where the error occurred?

https://manager.gitcoin.co/#/chain/1329/round/12

### What happened?

Page does not load any applications despite 179 applications being received.

Suspect improperly formatted application is the root cause, since indexer is replying with the full list and the other SEI round loads as expected.
![image](https://github.com/user-attachments/assets/82807981-2a03-48a2-99d4-eeae395897d3)

### What should have happened instead?

Page should display round apps

### Steps to Reproduce

Go to https://manager.gitcoin.co/#/chain/1329/round/12
impersonating `0x012dDEb107697252BDA3231a249d4d3bf747EAB6`

### What browser(s) are you seeing the problem on?

Chrome

### What chain(s) did the error occur on?

SEI

### Relevant log output

```shell
useApplicationsByRoundId TypeError: Cannot read properties of null (reading 'application')
    at utils.ts:266:37
    at Array.flatMap (<anonymous>)
    at g (utils.ts:249:66)
    at useApplicationsByRoundId.tsx:24:14
    at async index.mjs:253:23
```

**Comment by MasterHW** [comment]
fixed by https://github.com/gitcoinco/grants-stack/pull/3657
